### PR TITLE
Fix air flow when there is no air climate control on the network

### LINKED ISSUE #7: No climate control shouldn't stop the network from working.
AKA "Vents aren't dumping air!" (titled by HowMuhKevinNah)
https://steamcommunity.com/workshop/filedetails/discussion/973091113/2572002906850246840/

The whole network shouldn't stop working if there isn't any air climate control.

My air intake is as hot or cold as I need them to be.
I shouldn't need to waste 200W just to have something just sitting there doing unneeded heating/cooling adjustment.

This suggest it was intented to work without an air climate control unit:
https://github.com/vasumahesh1/CentralizedClimateControlMod/blob/9e373de2139b2c5fda1b88858ebd62ee8459f9f4/Source/CentralizedClimateControl/AirFlowNet.cs#L113-L118

Bug lies with how `ThermalCapacity == 0` means `ThermalEfficiency == 0`
https://github.com/vasumahesh1/CentralizedClimateControlMod/blob/9e373de2139b2c5fda1b88858ebd62ee8459f9f4/Source/CentralizedClimateControl/AirFlowNet.cs#L156-L159

And that leads to the `thermalFlag` being set which shut off the network.
https://github.com/vasumahesh1/CentralizedClimateControlMod/blob/6f44d98246d0914137d1015094315966b0dcfdc1/Source/CentralizedClimateControl/Building_AirVent.cs#L87-L90

### PR DESCRIPTION
**Pull request by asl97**
Fixes #7

### CODE REVIEW

**Comment by vasumahesh1** [comment]
Thanks I'll test this out next week! (Hopefully Saturday or Sunday!)

**Comment by vasumahesh1** [comment]
Thanks, Sorry for the delay. The changes look good to me. I will test this out soon with the game.

Also, please add your name to `Misc/Text` under Authors and a favorable URL.

**Comment by vasumahesh1** [comment]
Thanks, Sorry for the delay. The changes look good to me. I will test this out soon with the game.

Also, please add your name to `Misc/Text` under Authors and a favorable URL.

**Comment by asl97** [comment]
It's fine, it's really just a three line change with one part being refactor so that it's all in one place.

If it bother you that much, you can just do it your way and include it, everything you need is publicly available on my github profile.

Not to mention, if this is properly merge through the github merge button or through the [patch](https://patch-diff.githubusercontent.com/raw/vasumahesh1/CentralizedClimateControlMod/pull/9.patch) using git
(or manually using `--author` when using `git commit`).

Then they can find out the authors using github's [contributors](https://github.com/vasumahesh1/CentralizedClimateControlMod/graphs/contributors) or a git command: `git shortlog -s -n -e`

**Comment by vasumahesh1** [comment]
Alright, Sorry for the spam. Github showed me some 500 internal server errors!

**Comment by Undone** [comment]
I didn't notice this commit and ended up with the same fix, any chance of merging this?

**Pull request merged**
